language: php

php: ["5.3", "5.4", "5.5"]

env:
  global:
    - ARCHER_PUBLISH_VERSION=5.5
    - secure: "AcV7sTTDS29/wmn+mZjhBeDN7wHNJ4JVMcMrtzrjXuM8TM62YcI0C9Ih1kFM9H0aGAV2MZ5C6TNkG0W1Nc6QA2tx53rdQdsfUMc6YtNrTIeJZlLHC0sp1u4A5ZCOyKLooHNbB7ityENY3KGex7AifC8RkB+1DthM4WdiAWYvvoE="

install:
  - ./.travis.install

script:
  - ./vendor/bin/archer travis:build
